export const ACCESS_TOKEN_TTL_SECONDS = 60 * 15;
export const REFRESH_TOKEN_TTL_SECONDS = 60 * 60 * 24 * 7;
export const PASSWORD_RESET_TOKEN_TTL_MINUTES = 30;
export const EMAIL_VERIFICATION_TOKEN_TTL_HOURS = 24;
export const INVITE_TTL_DAYS = 7;
export const AUTH_RATE_LIMIT_WINDOW_MINUTES = 15;
export const AUTH_RATE_LIMIT_ATTEMPTS = 5;
